project:
  type: website
  output-dir: docs

website:
  title: Beck Tolle
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - project.qmd
    
    tools:
      - icon: trash
        href: https://redhotchilipeppers.com/
      - icon: github
        href: https://github.com/becktolle

format:
  html:
    theme: lux  # flatly, litera, lumen, lux, minty, pulse, sandstone, zephyr, quartz, yeti, cosmo, sketchy
    css: styles.css
    toc: true

execute: 
  freeze: auto

